In [2]:
import numpy as np 

var = np.array([13  ,8 ,10, 13])

print("min:",np.min(var))
print("max:",np.max(var))

min: 8
max: 13


In [3]:
var = np.array([13  ,8 ,10, 13])

print("min:",np.min(var),np.argmin(var))
print("max:",np.max(var),np.argmax(var))

min: 8 1
max: 13 0


In [8]:
var11= np.array([[1,2,3,4],[1,2,3,4]])
print(np.min(var11,axis=1))

[1 1]


In [11]:
import numpy as np
var = np.array([13  ,8 ,10, 13])

print("min:",np.min(var),np.argmin(var))
print("max:",np.max(var),np.argmax(var))
print('sqrt :',np.sqrt(var))

min: 8 1
max: 13 0
sqrt : [3.60555128 2.82842712 3.16227766 3.60555128]


In [12]:
var = np.array([13  ,8 ,10, 13])
print(np.sin(var))

[ 0.42016704  0.98935825 -0.54402111  0.42016704]


In [13]:
var = np.array([13  ,8 ,10, 13])
print(np.cos(var))

[ 0.90744678 -0.14550003 -0.83907153  0.90744678]


In [14]:
var = np.array([13  ,8 ,10, 13])
print(np.cumsum(var))

[13 21 31 44]
