In [3]:
import numpy as np 

var = np.array([13  ,8 ,10, 13])
varadd = var +5
print(varadd)

[18 13 15 18]


In [4]:
 
var1= np.array([1,2,3,4])
var2 = np.array([13  ,8 ,10, 13])
varadd = var1 + var2
print(varadd)

[14 10 13 17]


In [5]:
var1= np.array([1,2,3,4])
var2 = np.array([13  ,8 ,10, 13])
varsub = var1 - var2
print(varsub)

[-12  -6  -7  -9]


In [6]:
var1= np.array([1,2,3,4])
var2 = np.array([13  ,8 ,10, 13])
varadd = var1 * var2
print(varadd)

[13 16 30 52]


In [7]:
var1= np.array([1,2,3,4])
var2 = np.array([13  ,8 ,10, 13])
varadd = var1/var2
print(varadd)

[0.07692308 0.25       0.3        0.30769231]


In [8]:
var1= np.array([1,2,3,4])
var2 = np.array([13  ,8 ,10, 13])
varadd = np.add(var1,var2)
print(varadd)

[14 10 13 17]


In [9]:
var11= np.array([[1,2,3,4],[1,2,3,4]])
var21 = np.array([[1,2,3,4],[1,2,3,4]])

varadd = np.add(var11,var21)
print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


In [10]:
import numpy as np 

var = np.array([13  ,8 ,10, 13])
varadd =np.reciprocal(var)
print(varadd)

[0 0 0 0]
