In [2]:
import numpy as np 


var2 = np.array([13  ,8 ,10, 13])
print("data type:",var2.dtype)


data type: int64


In [3]:

var2 = np.array([13  ,8 ,10, 1.3])
print("data type:",var2.dtype)

data type: float64


In [4]:

var2 = np.array([13  ,'A',10, 13])
print("data type:",var2.dtype)

data type: <U21


In [5]:
var2 = np.array([13 ,10, 13])
print("data type:",var2.dtype)

data type: int64


In [7]:
var2 = np.array([13 ,10, 13],dtype=np.int8)
print("data type:",var2.dtype)
print(var2)

data type: int8
[13 10 13]


In [8]:
var2 = np.array([13 ,10, 13],dtype="f")
print("data type:",var2.dtype)
print(var2)

data type: float32
[13. 10. 13.]


In [9]:
x= np.array([1,2,3,4])
new=np.float32(x)

print("data type:",x.dtype)
print("data type:",new.dtype)
print(x)
print(new)

data type: int64
data type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [10]:
x= np.array([1,2,3,4])
new=np.float32(x)
new1=np.int_(new)

print("data type:",x.dtype)
print("data type:",new.dtype)
print("data type:",new1.dtype)
print(x)
print(new)
print(new1)

data type: int64
data type: float32
data type: int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]
