In [1]:
import numpy as np 

var=np.array([1,2,3,4,5])
print(var)
for i in var:
    print(i)

[1 2 3 4 5]
1
2
3
4
5


In [3]:
var=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(var)
for j in var:
    print(j)

print()

for k in var:
       for l in k:
           print(l)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[1 2 3 4 5]
[1 2 3 4 5]

1
2
3
4
5
1
2
3
4
5


In [5]:
var=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(var)

for i in np.nditer(var):
    print(i)

[[1 2 3 4 5]
 [1 2 3 4 5]]
1
2
3
4
5
1
2
3
4
5


In [6]:
var=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(var)

for i,d in np.ndenumerate(var):
    print(i,d)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 1
(1, 1) 2
(1, 2) 3
(1, 3) 4
(1, 4) 5
