In [10]:
import numpy as np

x=[1,2,3,4]

y= np.array([1,2,3,4])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [2]:
y

array([1, 2, 3, 4])

In [3]:
print(type(x))

<class 'list'>


In [9]:
l =[]

for i in range (1,5):
    int_1=int(input("enter:"))
    l.append(int_1)
print(np.array(l))

enter: 15
enter: 14
enter: 17
enter: 16


[15 14 17 16]


In [12]:
ar2=np.array([[1 ,2 ,3 ,4],[1, 2 ,3, 4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [13]:
ar3=np.array([[[1 ,2 ,3 ,4],[1, 2 ,3, 4],[1, 2 ,3, 4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [15]:
arn = np.array([1, 2 ,3, 4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [16]:
ar_zero=np.zeros(4)

print(ar_zero)

[0. 0. 0. 0.]


In [18]:
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))

print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
ar_one=np.ones(4)


print(ar_one)


[1. 1. 1. 1.]


In [21]:
ar_em=np.empty(4)


print(ar_em)


[1. 1. 1. 1.]


In [22]:
ar_rn=np.arange(4)


print(ar_rn)


[0 1 2 3]


In [23]:
ar_dia=np.eye(3)
print(ar_dia)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [25]:
ar_lin=np.linspace(1,10,num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
