In [2]:
import numpy as np 

var = np.random.rand(4)
print(var)



[0.61765804 0.69425476 0.05747563 0.04961182]


In [3]:
import numpy as np 

var1 = np.random.rand(4,7)
print(var1)

[[0.42790094 0.43435803 0.54693151 0.97110617 0.5442535  0.79185717
  0.14869316]
 [0.57853871 0.80306226 0.09971942 0.57374363 0.65825639 0.98191699
  0.34530595]
 [0.10322416 0.10941046 0.94911117 0.96402718 0.29860571 0.38212019
  0.30220203]
 [0.56500623 0.54896063 0.33878866 0.43607913 0.56205781 0.44416645
  0.23358851]]


In [4]:
import numpy as np 

var2 = np.random.randn(4)
print(var2)


[ 0.61777493 -1.38560241 -0.34689051 -0.46771226]


In [6]:
import numpy as np 

var3 = np.random.ranf(4)
print(var3)

[0.73850215 0.01795086 0.93339607 0.31915923]


In [8]:
import numpy as np 

var4 = np.random.randint(4,17,4)
print(var4)


[13  8 10 13]
