In [3]:
import numpy as np

var = np.array([[1,2],[1,2]])
print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [7]:

var1 = np.array([1,2,8,9],ndmin=4)
print(var1)
print(var1.ndim)

[[[[1 2 8 9]]]]
4


In [8]:
var1 = np.array([1,2,8,9],ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[1 2 8 9]]]]
4
(1, 1, 1, 4)


In [17]:
var1 = np.array([1,2,3,4,5,6])
print(var1)

x=var1.reshape(2,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
2


In [ ]:
var1 = np.array([1,2,3,4,5,6])
print(var1)

x=var1.reshape(2,3)
print(x)
print(x.ndim) 